In [1]:
import os
print(os.getcwd())

/Users/qianxigong/Documents/108/gnnbackup/log


In [2]:
pth = "/Users/qianxigong/Downloads/Introspection"

firstlevel_firstcsp=["righttomid","midtoright"] # classify two direction in right hand 
firstlevel_secondcsp=["lefttomid","midtoleft"] # classify two direction in left hand 

secondlevel_firstcsp=["midtoleft","midtoright"] # classify right vs left in direction 1
secondlevel_secondcsp=["lefttomid","righttomid"]# classify right vs left in direction 2

In [3]:
label_lookup = {
    (0, 0, 0): [6, 7, 7, 7, 8, 9, 9, 9, 10, 11, 11, 11],
    (0, 0, 1): [6, 6, 7, 7, 8, 8, 9, 9, 10, 10, 11, 11],
    (0, 0, 2): [6, 6, 6, 7, 8, 8, 8, 9, 10, 10, 10, 11],
    (0, 1, 0): [5, 4, 4, 4, 3, 2, 2, 2, 1, 0, 0, 0],
    (0, 1, 1): [5, 5, 4, 4, 3, 3, 2, 2, 1, 1, 0, 0],
    (0, 1, 2): [5, 5, 5, 4, 3, 3, 3, 2, 1, 1, 1, 0],
    (1, 0, 0): [11, 10, 10, 10, 9, 8, 8, 8, 7, 6, 6, 6],
    (1, 0, 1): [11, 11, 10, 10, 9, 9, 8, 8, 7, 7, 6, 6],
    (1, 0, 2): [11, 11, 11, 10, 9, 9, 9, 8, 7, 7, 7, 6],
    (1, 1, 0): [0, 1, 1, 1, 2, 3, 3, 3, 4, 5, 5, 5],
    (1, 1, 1): [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5],
    (1, 1, 2): [0, 0, 0, 1, 2, 2, 2, 3, 4, 4, 4, 5],
}

In [4]:
#u, i, ts, label, idx, which represents source node index, target node index, time stamp, edge label and the edge index. 

complet = {key: [x + 2 for x in value] for key, value in label_lookup.items()}
complete = {key: [1, *value] for key, value in complet.items()}
#start from 1 (new state)
source_node_dic = {key: value[:-1] for key, value in complete.items()}
target_node_dic = {key: value[1:] for key, value in complete.items()}
target_node_dic

{(0, 0, 0): [8, 9, 9, 9, 10, 11, 11, 11, 12, 13, 13, 13],
 (0, 0, 1): [8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13],
 (0, 0, 2): [8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 12, 13],
 (0, 1, 0): [7, 6, 6, 6, 5, 4, 4, 4, 3, 2, 2, 2],
 (0, 1, 1): [7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2],
 (0, 1, 2): [7, 7, 7, 6, 5, 5, 5, 4, 3, 3, 3, 2],
 (1, 0, 0): [13, 12, 12, 12, 11, 10, 10, 10, 9, 8, 8, 8],
 (1, 0, 1): [13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8, 8],
 (1, 0, 2): [13, 13, 13, 12, 11, 11, 11, 10, 9, 9, 9, 8],
 (1, 1, 0): [2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 7, 7],
 (1, 1, 1): [2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7],
 (1, 1, 2): [2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 6, 7]}

In [5]:
source_node_dic

{(0, 0, 0): [1, 8, 9, 9, 9, 10, 11, 11, 11, 12, 13, 13],
 (0, 0, 1): [1, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13],
 (0, 0, 2): [1, 8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 12],
 (0, 1, 0): [1, 7, 6, 6, 6, 5, 4, 4, 4, 3, 2, 2],
 (0, 1, 1): [1, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2],
 (0, 1, 2): [1, 7, 7, 7, 6, 5, 5, 5, 4, 3, 3, 3],
 (1, 0, 0): [1, 13, 12, 12, 12, 11, 10, 10, 10, 9, 8, 8],
 (1, 0, 1): [1, 13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8],
 (1, 0, 2): [1, 13, 13, 13, 12, 11, 11, 11, 10, 9, 9, 9],
 (1, 1, 0): [1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 7],
 (1, 1, 1): [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7],
 (1, 1, 2): [1, 2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 6]}

In [6]:
import time
from datetime import datetime , timedelta
import numpy as np
def generate_timestamps(num_timestamps):
    # Get the current timestamp
    now = datetime.now()
    timestamps = [(now + timedelta(milliseconds=250 * i)).timestamp() for i in range(num_timestamps)]
    return np.array(timestamps)

# Generate and save timestamps
timestamps = generate_timestamps(108 * 12 *250 )
np.save('timestamps.npy', timestamps)

# Load timestamps when needed
ts = np.load('timestamps.npy')


In [8]:
sampled_ts = ts[::250]

In [9]:
len(sampled_ts)

1296

In [10]:
sampled_ts


array([1.69440971e+09, 1.69440977e+09, 1.69440984e+09, ...,
       1.69449052e+09, 1.69449059e+09, 1.69449065e+09])

In [27]:
import pandas as pd
import numpy as np

timestamps = sampled_ts
# Create DataFrame
df = pd.DataFrame({
    'u': [np.nan] * len(timestamps),
    'i': [np.nan] * len(timestamps),
    'ts': timestamps,
    'label': [np.nan] * len(timestamps),
    'idx': [np.nan] * len(timestamps),
})

# Save DataFrame to csv
df.to_csv('ml_hands.csv', index=False)

In [14]:
source_node_dic

{(0, 0, 0): [1, 8, 9, 9, 9, 10, 11, 11, 11, 12, 13, 13],
 (0, 0, 1): [1, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13],
 (0, 0, 2): [1, 8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 12],
 (0, 1, 0): [1, 7, 6, 6, 6, 5, 4, 4, 4, 3, 2, 2],
 (0, 1, 1): [1, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2],
 (0, 1, 2): [1, 7, 7, 7, 6, 5, 5, 5, 4, 3, 3, 3],
 (1, 0, 0): [1, 13, 12, 12, 12, 11, 10, 10, 10, 9, 8, 8],
 (1, 0, 1): [1, 13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8],
 (1, 0, 2): [1, 13, 13, 13, 12, 11, 11, 11, 10, 9, 9, 9],
 (1, 1, 0): [1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 7],
 (1, 1, 1): [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7],
 (1, 1, 2): [1, 2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 6]}

In [15]:
import sys
sys.path.append('/Users/qianxigong/Downloads/introspection/models')

In [16]:

from torch.utils.data import DataLoader, TensorDataset
from trainingg import get_train_data_dic
from sklearn.model_selection import train_test_split

batch_size=1
midstartlst=['righttomid',"lefttomid"]
midendlst=['midtoleft',"midtoright"]
directions=[midstartlst,midendlst]

rightlst=['righttomid','midtoright']
leftlst=['midtoleft', 'lefttomid']
positions=[rightlst, leftlst]

speeds=["fast", "even", "slow"]
#load one X and 3Y
X_list=[]
Y1=[]
Y2=[]
Y3=[]
for speed in speeds:
    label3=speeds.index(speed) #["fast", "even", "slow"]
    for groups in directions: #[midstartlst,midendlst]
        label1=directions.index(groups) #two direction
        for single in groups:
            if single in rightlst:
                label2= 0
            elif single in leftlst:
                label2= 1
            dic= get_train_data_dic([single], speed)
            X_list.append(dic[single]) # 9,8 1500 #12,9,8,1500
            Y1+=[label1]*len(dic[single])
            Y2+=[label2]*len(dic[single])
            Y3+=[label3]*len(dic[single])
# print(len(X_list), len(X_list[0]))
X = np.vstack(X_list)
X = np.squeeze(X, axis=1)
Y1, Y2, Y3= np.array(Y1),np.array(Y2),np.array(Y3)
Y_combined = np.vstack((Y1, Y2, Y3)).T
X_train, X_test, Y_train, Y_test = train_test_split(X, Y_combined, test_size=0.2)

# # Create TensorDatasets for the training and validation sets
# train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32), torch.tensor(Y_train,dtype=torch.long))
# val_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32), torch.tensor(Y_test,dtype=torch.long))

# # Create DataLoaders for the training and validation sets
# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,drop_last=True)

# val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False,drop_last=True)


/Users/qianxigong/miniforge3/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/qianxigong/miniforge3/lib/python3.9/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
  Referenced from: <7968D834-00B6-3BC5-91B8-63E6BB9C4E4E> /Users/qianxigong/miniforge3/lib/python3.9/site-packages/torchvision/image.so
  Expected in:     <F008E7E7-AB21-3358-8168-A868137DB04F> /Users/qianxigong/miniforge3/lib/python3.9/site-packages/torch/lib/libtorch_cpu.dylib
  warn(f"Failed to load image Python extension: {e}")


righttomid
lefttomid
midtoleft
midtoright
righttomid
lefttomid
midtoleft
midtoright
righttomid
lefttomid
midtoleft
midtoright


In [17]:
X.shape

(108, 8, 1500)

In [18]:
Y_combined.shape

(108, 3)

In [19]:
target_node_dic

{(0, 0, 0): [8, 9, 9, 9, 10, 11, 11, 11, 12, 13, 13, 13],
 (0, 0, 1): [8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13, 13],
 (0, 0, 2): [8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 12, 13],
 (0, 1, 0): [7, 6, 6, 6, 5, 4, 4, 4, 3, 2, 2, 2],
 (0, 1, 1): [7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2, 2],
 (0, 1, 2): [7, 7, 7, 6, 5, 5, 5, 4, 3, 3, 3, 2],
 (1, 0, 0): [13, 12, 12, 12, 11, 10, 10, 10, 9, 8, 8, 8],
 (1, 0, 1): [13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8, 8],
 (1, 0, 2): [13, 13, 13, 12, 11, 11, 11, 10, 9, 9, 9, 8],
 (1, 1, 0): [2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 7, 7],
 (1, 1, 1): [2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7],
 (1, 1, 2): [2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 6, 7]}

In [20]:


# righttomid
# lefttomid
# midtoleft
# midtoright

In [22]:
source_node_dic

{(0, 0, 0): [1, 8, 9, 9, 9, 10, 11, 11, 11, 12, 13, 13],
 (0, 0, 1): [1, 8, 8, 9, 9, 10, 10, 11, 11, 12, 12, 13],
 (0, 0, 2): [1, 8, 8, 8, 9, 10, 10, 10, 11, 12, 12, 12],
 (0, 1, 0): [1, 7, 6, 6, 6, 5, 4, 4, 4, 3, 2, 2],
 (0, 1, 1): [1, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 2],
 (0, 1, 2): [1, 7, 7, 7, 6, 5, 5, 5, 4, 3, 3, 3],
 (1, 0, 0): [1, 13, 12, 12, 12, 11, 10, 10, 10, 9, 8, 8],
 (1, 0, 1): [1, 13, 13, 12, 12, 11, 11, 10, 10, 9, 9, 8],
 (1, 0, 2): [1, 13, 13, 13, 12, 11, 11, 11, 10, 9, 9, 9],
 (1, 1, 0): [1, 2, 3, 3, 3, 4, 5, 5, 5, 6, 7, 7],
 (1, 1, 1): [1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7],
 (1, 1, 2): [1, 2, 2, 2, 3, 4, 4, 4, 5, 6, 6, 6]}

In [ ]:
#(108, 8, 1500), (108, 3)

seqlength = 12

for seq, nottup in zip(X,Y_combined):
    tup = tuple(nottup)
    nan_indices = df[df['u'].isna()].index.tolist()
    indices_to_update = nan_indices[:seqlength] 
    df.loc[indices_to_update, 'u'] = [int(itm) for itm in source_node_dic[tup]]
    df.loc[indices_to_update, 'i'] = [int(itm) for itm in target_node_dic[tup]]
    df.loc[indices_to_update, 'label'] =  [str(tup) for _ in range(len(indices_to_update))]   
    print(seq.shape)
df.to_csv('ml_hands.csv', index=False)


In [31]:
df["idx"] = df.index.tolist()

In [32]:
df

u     i            ts      label   idx
0      1.0   8.0  1.692341e+09  (0, 0, 0)     0
1      8.0   9.0  1.692341e+09  (0, 0, 0)     1
2      9.0   9.0  1.692341e+09  (0, 0, 0)     2
3      9.0   9.0  1.692341e+09  (0, 0, 0)     3
4      9.0  10.0  1.692341e+09  (0, 0, 0)     4
...    ...   ...           ...        ...   ...
1291  11.0  10.0  1.692421e+09  (1, 0, 2)  1291
1292  10.0   9.0  1.692421e+09  (1, 0, 2)  1292
1293   9.0   9.0  1.692421e+09  (1, 0, 2)  1293
1294   9.0   9.0  1.692421e+09  (1, 0, 2)  1294
1295   9.0   8.0  1.692421e+09  (1, 0, 2)  1295

[1296 rows x 5 columns]

In [57]:
edge_features = np.concatenate([x.reshape(12,-1) for x in X], axis=0)

node_features =  np.repeat(Y_combined, 12, axis=0)

In [58]:
node_features.shape

(1296, 3)

In [53]:
edge_features.shape

(1296, 1000)

In [33]:
df.to_csv('ml_hands.csv', index=False)

In [61]:
#ml_${DATA_NAME}.npy` has shape of [#temporal edges + 1, edge features dimention]. Similarly, `ml_${DATA_NAME}_node.npy` has shape of [#nodes + 1, node features dimension].
#1296 8*250

DATA_NAME = "hands"
temporal_edges = df["idx"].iloc[-1]
edge_features_dim = 8*250
edge_features_array = np.zeros((temporal_edges + 1, edge_features_dim))
edge_features_array.shape
np.save(f"ml_{DATA_NAME}.npy", edge_features_array)
np.save(f"ml_{DATA_NAME}_node.npy", edge_features_array)

In [60]:
os.chdir('/Users/qianxigong/Downloads/drive-download-20230814T091829Z-001/processed')


In [ ]:
import torch
import torch.nn as nn
import numpy as np

class ChannelEmbedding(nn.Module):
    def __init__(self, d_model, ch_names):
        super(ChannelEmbedding, self).__init__()
        self.d_model = d_model
        self.ch_names = ch_names
        self.embedding = torch.zeros(len(ch_names), d_model)
        self.create_embedding()
        
    def create_embedding(self):
        # Assign relative positions based on your description
        # Closer to the center means a smaller number
        ch_position = {
            "Cz": 0,
            "CPz": 1,
            "CP3": 2, "CP4": 2,
            "CP5": 3, "CP6": 3,
            "P7": 4, "P8": 4
        }
        
        for pos, ch_name in enumerate(self.ch_names):
            position = ch_position[ch_name]
            div_term = torch.exp(torch.arange(0, self.d_model, 2).float() * -(np.log(10000.0) / self.d_model))
            self.embedding[pos, 0::2] = torch.sin(position * div_term)
            self.embedding[pos, 1::2] = torch.cos(position * div_term)
            
        self.embedding = nn.Parameter(self.embedding, requires_grad=False)
            
    def forward(self, x):
        # Assuming x is of shape [N, L, d_model] where L is the number of channels and matches len(ch_names)
        return x + self.embedding


In [ ]:
ch_names = ["P7", "CP5", "CP3", "CPz", "Cz", "CP4", "CP6", "P8"]
d_model = 8  # smaller for easy visualization
channel_emb = ChannelEmbedding(d_model, ch_names)
print(channel_emb.embedding)


Parameter containing:
tensor([[-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e-01],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  9.9833e-02,  9.9500e-01,  9.9998e-03,
          9.9995e-01,  1.0000e-03,  1.0000e+00],
        [ 0.0000e+00,  1.0000e+00,  0.0000e+00,  1.0000e+00,  0.0000e+00,
          1.0000e+00,  0.0000e+00,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  1.9867e-01,  9.8007e-01,  1.9999e-02,
          9.9980e-01,  2.0000e-03,  1.0000e+00],
        [ 1.4112e-01, -9.8999e-01,  2.9552e-01,  9.5534e-01,  2.9995e-02,
          9.9955e-01,  3.0000e-03,  1.0000e+00],
        [-7.5680e-01, -6.5364e-01,  3.8942e-01,  9.2106e-01,  3.9989e-02,
          9.9920e-01,  4.0000e-03,  9.9999e

In [ ]:
x = torch.randn(5, len(ch_names), d_model)  # Example tensor for 5 samples
embedded_x = channel_emb(x)
print(embedded_x)


tensor([[[ 2.3780e-01, -1.6251e+00, -1.3106e-01, -4.2696e-01,  1.0959e+00,
           1.2949e+00,  3.5198e-01,  7.3994e-01],
         [-1.2343e+00, -7.2173e-01,  6.1617e-01,  5.3011e-01, -1.2291e-01,
           2.1230e-01, -4.6051e-01,  6.8829e-01],
         [ 1.6378e-02, -1.1625e+00, -6.0013e-01,  1.7253e+00, -1.3905e+00,
          -4.9244e-01, -4.6237e-01, -7.8519e-01],
         [ 5.4876e-01, -8.9679e-01,  1.4695e+00,  1.0858e-01, -1.6832e-02,
           6.4576e-01,  2.3079e+00,  1.3980e-01],
         [-9.7770e-01,  1.0224e+00,  3.5229e+00,  8.2300e-01, -1.0249e+00,
           4.8633e-01, -8.7128e-01,  1.0057e+00],
         [ 9.3842e-02, -1.0597e+00,  1.5036e-01,  1.0180e+00,  9.0615e-01,
           1.0801e+00, -2.0035e-01,  7.0203e-01],
         [ 8.3548e-01, -6.2218e-02, -1.1012e+00,  2.6887e+00,  8.9019e-01,
           2.1025e-01, -1.0468e+00, -7.9463e-02],
         [-1.5491e+00, -2.1211e+00,  4.8830e-01,  1.1173e+00, -9.0025e-01,
          -3.8913e-01,  1.3927e+00,  6.1311e-01]],

In [ ]:
from torch.nn.functional import cosine_similarity

# Pairwise cosine similarity
similarity_matrix = torch.zeros(len(ch_names), len(ch_names))
for i in range(len(ch_names)):
    for j in range(len(ch_names)):
        similarity_matrix[i, j] = cosine_similarity(channel_emb.embedding[i], channel_emb.embedding[j], dim=0)

print(similarity_matrix)


tensor([[1.0000, 0.8838, 0.6409, 0.4912, 0.5667, 0.6409, 0.8838, 1.0000],
        [0.8838, 1.0000, 0.8838, 0.6409, 0.4912, 0.8838, 1.0000, 0.8838],
        [0.6409, 0.8838, 1.0000, 0.8838, 0.6409, 1.0000, 0.8838, 0.6409],
        [0.4912, 0.6409, 0.8838, 1.0000, 0.8838, 0.8838, 0.6409, 0.4912],
        [0.5667, 0.4912, 0.6409, 0.8838, 1.0000, 0.6409, 0.4912, 0.5667],
        [0.6409, 0.8838, 1.0000, 0.8838, 0.6409, 1.0000, 0.8838, 0.6409],
        [0.8838, 1.0000, 0.8838, 0.6409, 0.4912, 0.8838, 1.0000, 0.8838],
        [1.0000, 0.8838, 0.6409, 0.4912, 0.5667, 0.6409, 0.8838, 1.0000]])
